[package]
name = "egui_dnd"
version = "0.1.0"
edition = "2021"
authors = ["Lucas Meurer"]
repository = "https://github.com/lucasmerlin/egui_dnd"
keywords = ["egui", "drag", "drop", "ui"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.20.1"
